export const ACTION_SEARCH_USER_LOADING = 'ACTION_SEARCH_USER_LOADING';
export const ACTION_SEARCH_USER_ERROR = 'ACTION_SEARCH_USER_ERROR';
export const ACTION_SEARCH_USER_SUCCESS = 'ACTION_SEARCH_USER_SUCCESS';
